"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app
"""

from setuptools import setup

APP = ['GUI.py']
DATA_FILES = ['error_icon.gif', 'warning_icon.gif'] 
OPTIONS = {
    'iconfile':'cold_call.icns',
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
